import React,{useEffect,useMemo,useState} from 'react'
import {Home,Flag,Dumbbell,BookOpen,BarChart3,Plus,ChevronLeft,ChevronRight,Save,Link2,Cloud,CloudOff} from 'lucide-react'
import {collection,doc,getDocs,onSnapshot,query,setDoc,where} from 'firebase/firestore'
import {db,ensureUser,firebaseEnabled} from './firebase'

const R=['◎','○','△','×'], SCORES=[3,4,5,6,7,8,9,10]
const CLUBS=['ドライバー','FW','UT','アイアン','ウェッジ','パター']
const MISSES=['スライス','フック','チーピン','天ぷら','トップ','ダフリ']
const initial={courses:[{id:'river',name:'河川敷ショートコース',pars:[4,3,4,3,4,3,4,3,4]}],players:['井関','メンバー2','メンバー3'],logs:[],round:null}
const code=()=>Math.random().toString(36).slice(2,8).toUpperCase()
const read=()=>{try{return {...initial,...JSON.parse(localStorage.getItem('golf-growth-data')||'{}')}}catch{return initial}}

export default function App(){
 const [data,setData]=useState(read),[screen,setScreen]=useState('home'),[hole,setHole]=useState(0),[courseId,setCourseId]=useState(read().courses[0].id),[joinCode,setJoinCode]=useState(''),[msg,setMsg]=useState('')
 const [draftCourse,setDraftCourse]=useState({name:'',pars:[4,3,4,3,4,3,4,3,4]})
 const [practice,setPractice]=useState({club:'ドライバー',direction:'中央',misses:[],improvement:'',result:'○',memo:''})
 useEffect(()=>localStorage.setItem('golf-growth-data',JSON.stringify(data)),[data])
 useEffect(()=>{if(!firebaseEnabled||!data.round?.id)return; let off; ensureUser().then(()=>{off=onSnapshot(doc(db,'rounds',data.round.id),s=>{if(s.exists())setData(d=>({...d,round:s.data()}))})}); return()=>off?.()},[data.round?.id])
 const note=t=>{setMsg(t);setTimeout(()=>setMsg(''),1800)}
 const course=data.courses.find(c=>c.id===courseId)||data.courses[0]
 async function syncRound(round){setData(d=>({...d,round}));if(firebaseEnabled){await ensureUser();await setDoc(doc(db,'rounds',round.id),round);}}
 async function start(){const players=data.players.map((p,i)=>p.trim()||`メンバー${i+1}`);const round={id:code(),courseName:course.name,players,date:new Date().toISOString(),holes:course.pars.map(par=>({par,scores:Object.fromEntries(players.map(p=>[p,null])),ratings:Object.fromEntries(players.map(p=>[p,{tee:null,approach:null,putt:null}]))}))};setData(d=>({...d,players}));await syncRound(round);setHole(0);setScreen('round')}
 async function join(){if(!firebaseEnabled)return note('Firebase設定後に利用できます');await ensureUser();const q=query(collection(db,'rounds'),where('id','==',joinCode.trim().toUpperCase()));const s=await getDocs(q);if(s.empty)return note('参加コードが見つかりません');setData(d=>({...d,round:s.docs[0].data(),players:s.docs[0].data().players}));setScreen('round')}
 async function score(p,n){const r={...data.round,holes:data.round.holes.map((h,i)=>i===hole?{...h,scores:{...h.scores,[p]:n}}:h)};await syncRound(r)}
 async function rating(p,t,v){const r={...data.round,holes:data.round.holes.map((h,i)=>i===hole?{...h,ratings:{...h.ratings,[p]:{...h.ratings[p],[t]:v}}}:h)};await syncRound(r)}
 const totals=useMemo(()=>data.round?Object.fromEntries(data.round.players.map(p=>[p,data.round.holes.reduce((a,h)=>a+(h.scores[p]||0),0)])):{},[data.round])
 function saveLog(){if(!practice.improvement.trim())return note('改善内容を入力してください');setData(d=>({...d,logs:[{...practice,id:code(),date:new Date().toISOString()},...d.logs]}));setPractice(p=>({...p,misses:[],improvement:'',memo:''}));setScreen('notes')}
 const nav=[['home',Home,'ホーム'],['round',Flag,'ラウンド'],['practice',Dumbbell,'練習'],['notes',BookOpen,'改善'],['summary',BarChart3,'結果']]
 return <div className="app"><header><div className="brand"><span><Flag size={20}/></span><div><small>GOLF GROWTH</small><b>成長スコアブック</b></div></div><i title={firebaseEnabled?'Firebase接続':'ローカルモード'}>{firebaseEnabled?<Cloud/>:<CloudOff/>}</i>{data.round&&<button className="code" onClick={()=>{navigator.clipboard?.writeText(data.round.id);note('参加コードをコピー')}}><Link2 size={14}/>{data.round.id}</button>}</header><main>
 {screen==='home'&&<div className="stack"><section className="hero"><small>練習からラウンドまで</small><h1>ゴルフの成長を<br/>ひとつに記録</h1><p>スコア、ショット評価、試した改善をシンプルに蓄積。</p></section><Card><Label>コース</Label><select value={courseId} onChange={e=>setCourseId(e.target.value)}>{data.courses.map(c=><option key={c.id} value={c.id}>{c.name} / Par {c.pars.reduce((a,b)=>a+b,0)}</option>)}</select><Label>参加メンバー</Label>{data.players.map((p,i)=><input key={i} value={p} onChange={e=>setData(d=>({...d,players:d.players.map((x,j)=>j===i?e.target.value:x)}))}/>) }<Primary onClick={start}><Plus/>ラウンド開始</Primary></Card><Card><b>参加コードで入る</b><div className="row"><input value={joinCode} onChange={e=>setJoinCode(e.target.value.toUpperCase())} maxLength="6" placeholder="例 A1B2C3"/><button onClick={join}>参加</button></div></Card><button className="wide" onClick={()=>setScreen('courses')}>コースマスタを設定 <ChevronRight/></button></div>}
 {screen==='courses'&&<div className="stack"><Back onClick={()=>setScreen('home')}/><Title t="コースマスタ" s="9ホールのPar構成を事前登録"/>{data.courses.map(c=><Card key={c.id}><div className="between"><b>{c.name}</b><strong>Par {c.pars.reduce((a,b)=>a+b,0)}</strong></div><div className="pars">{c.pars.map((p,i)=><span key={i}><small>H{i+1}</small><b>{p}</b></span>)}</div></Card>)}<Card><input placeholder="新しいコース名" value={draftCourse.name} onChange={e=>setDraftCourse(v=>({...v,name:e.target.value}))}/><div className="pars">{draftCourse.pars.map((p,i)=><label key={i}><small>H{i+1}</small><select value={p} onChange={e=>setDraftCourse(v=>({...v,pars:v.pars.map((x,j)=>j===i?+e.target.value:x)}))}>{[3,4,5].map(n=><option key={n}>{n}</option>)}</select></label>)}</div><Primary onClick={()=>{if(!draftCourse.name.trim())return note('コース名を入力');const c={...draftCourse,id:code()};setData(d=>({...d,courses:[...d.courses,c]}));setCourseId(c.id);setDraftCourse({name:'',pars:[4,3,4,3,4,3,4,3,4]});note('保存しました')}}><Save/>保存</Primary></Card></div>}
 {screen==='round'&&data.round&&<div className="stack"><div className="holeHead"><button disabled={!hole} onClick={()=>setHole(h=>h-1)}><ChevronLeft/></button><div><small>{data.round.courseName}</small><h1>HOLE {hole+1}</h1><b>PAR {data.round.holes[hole].par}</b></div><button disabled={hole===8} onClick={()=>setHole(h=>h+1)}><ChevronRight/></button></div>{data.round.players.map(p=>{const h=data.round.holes[hole],s=h.scores[p];return <Card key={p}><div className="between"><h3>{p}</h3><strong className="score">{s||'-'}</strong></div><div className="scores">{SCORES.map(n=><button className={s===n?'active':''} onClick={()=>score(p,n)} key={n}>{n}</button>)}</div><div className="ratings">{[['tee','ティー'],['approach','アプローチ'],['putt','パット']].map(([t,l])=><div key={t}><small>{l}</small><span>{R.map(r=><button className={h.ratings[p][t]===r?'dark':''} onClick={()=>rating(p,t,r)} key={r}>{r}</button>)}</span></div>)}</div></Card>})}<Primary onClick={()=>hole<8?setHole(h=>h+1):setScreen('summary')}>{hole<8?'次のホールへ':'結果を見る'}</Primary></div>}
 {screen==='practice'&&<div className="stack"><Title t="練習カルテ" s="練習後に1分で振り返り"/><Card><Label>クラブ</Label><div className="choices">{CLUBS.map(x=><Choice a={practice.club===x} key={x} onClick={()=>setPractice(p=>({...p,club:x}))}>{x}</Choice>)}</div><Label>主な方向</Label><div className="choices five">{['左大','左','中央','右','右大'].map(x=><Choice a={practice.direction===x} key={x} onClick={()=>setPractice(p=>({...p,direction:x}))}>{x}</Choice>)}</div><Label>出たミス</Label><div className="choices">{MISSES.map(x=><Choice a={practice.misses.includes(x)} key={x} onClick={()=>setPractice(p=>({...p,misses:p.misses.includes(x)?p.misses.filter(m=>m!==x):[...p.misses,x]}))}>{x}</Choice>)}</div><Label>試した改善</Label><input value={practice.improvement} onChange={e=>setPractice(p=>({...p,improvement:e.target.value}))} placeholder="例 力まずゆっくり振る"/><Label>効果</Label><div className="choices four">{R.map(x=><Choice a={practice.result===x} key={x} onClick={()=>setPractice(p=>({...p,result:x}))}>{x}</Choice>)}</div><Label>メモ</Label><textarea value={practice.memo} onChange={e=>setPractice(p=>({...p,memo:e.target.value}))}/><Primary onClick={saveLog}>練習カルテを保存</Primary></Card></div>}
 {screen==='notes'&&<div className="stack"><Title t="改善ノート" s="効いた改善を次の練習へ"/>{!data.logs.length?<Card><p className="empty">まだ練習記録がありません</p></Card>:data.logs.map(l=><Card key={l.id}><div className="between"><div><strong>{l.club}</strong><small>{new Date(l.date).toLocaleDateString('ja-JP')}</small></div><b className="result">{l.result}</b></div><div className="improve"><small>試した改善</small><b>{l.improvement}</b></div><p>{l.misses.join('・')}</p>{l.memo&&<p>{l.memo}</p>}</Card>)}</div>}
 {screen==='summary'&&data.round&&<div className="stack"><section className="summary"><small>ROUND SUMMARY</small><h2>{data.round.courseName}</h2>{[...data.round.players].sort((a,b)=>totals[a]-totals[b]).map((p,i)=><div key={p}><span>{i+1}</span><b>{p}</b><strong>{totals[p]}</strong></div>)}</section><Card>{data.round.holes.map((h,i)=><button className="summaryRow" key={i} onClick={()=>{setHole(i);setScreen('round')}}><b>H{i+1} P{h.par}</b>{data.round.players.map(p=><span key={p}>{h.scores[p]||'-'}</span>)}</button>)}</Card></div>}
 </main><nav>{nav.map(([s,I,l])=><button className={screen===s?'active':''} key={s} onClick={()=>{if((s==='round'||s==='summary')&&!data.round)return note('先にラウンドを開始');setScreen(s)}}><I/><small>{l}</small></button>)}</nav>{msg&&<div className="toast">{msg}</div>}</div>
}
const Card=({children})=><section className="card">{children}</section>
const Label=({children})=><label className="label">{children}</label>
const Primary=({children,onClick})=><button className="primary" onClick={onClick}>{children}</button>
const Choice=({children,a,onClick})=><button className={`choice ${a?'selected':''}`} onClick={onClick}>{children}</button>
const Back=({onClick})=><button className="back" onClick={onClick}><ChevronLeft/>戻る</button>
const Title=({t,s})=><div className="title"><h2>{t}</h2><p>{s}</p></div>
