export const MISS=[
{id:'slice',name:'スライス',icon:'↗',desc:'打ち出した後、右へ大きく曲がる'},
{id:'hook',name:'フック',icon:'↖',desc:'打ち出した後、左へ曲がる'},
{id:'duck',name:'チーピン',icon:'↶',desc:'低く出て、急激に左へ曲がる'},
{id:'sky',name:'天ぷら',icon:'↑',desc:'真上へ高く上がり、飛距離が出ない'},
{id:'top',name:'トップ',icon:'⇢',desc:'ボール上部を打ち、低く転がる・飛ぶ'},
{id:'fat',name:'ダフリ',icon:'⌄',desc:'ボールより手前の地面を先に打つ'},
{id:'pull',name:'引っかけ',icon:'←',desc:'曲がる前から、最初から左へ飛ぶ'},
{id:'push',name:'プッシュ',icon:'→',desc:'曲がる前から、最初から右へ飛ぶ'}]
export const T={relax:['力を抜いて7割で振る','切り返しを急がず一定テンポで振る'],finish:['フィニッシュまで振り切る','胸が目標方向を向くまで回転する'],strong:['左手のナックルを少し多く見せる','フェースが開く傾向を小さく調整する'],neutral:['グリップをニュートラルへ戻す','フェースが閉じる傾向を小さく調整する'],teeLow:['ティーを少し低くする','高すぎる弾道や天ぷらの変化を見る'],teeHigh:['ティーを少し高くする','低すぎる弾道の変化を見る'],ballBack:['ボール位置を半個右へ','最下点の変化を確認する'],left:['左足体重を保つ','アプローチの体重移動を抑える'],chest:['手だけでなく胸で運ぶ','手首をこねず胸とクラブを一緒に動かす'],height:['前傾と頭の高さを保つ','上下動を減らす'],short:['振り幅を一段小さくする','芯に当たる振り幅から再開する'],aim:['フェースを合わせてから足を置く','目標線のずれを減らす'],tempo:['「1・2」のテンポで振る','切り返しのリズムを揃える'],putt:['頭を残してボールの跡を見る','打ち出し方向を安定させる']}
const rules=[{m:['slice'],t:['relax','finish','strong']},{m:['hook','duck','pull'],t:['neutral','aim','tempo']},{m:['sky'],t:['teeLow','height','short']},{m:['top'],t:['height','short','ballBack']},{m:['fat'],t:['ballBack','height','tempo']},{m:['push'],t:['finish','aim','tempo']},{d:['右','右大'],t:['finish','strong','aim']},{d:['左','左大'],t:['aim','neutral','relax']},{c:['ウェッジ'],m:['top','fat'],t:['left','chest','short']},{c:['パター'],t:['putt','aim','tempo']},{c:['ドライバー'],h:['高い'],t:['teeLow','relax','short']},{c:['ドライバー'],h:['低い'],t:['teeHigh','finish','tempo']}],pts={'◎':1,'○':.7,'△':.25,'×':0}
export function suggest(logs,f){let ids=[];rules.forEach(r=>{if((!r.c||r.c.includes(f.club))&&(!r.d||r.d.includes(f.direction))&&(!r.h||r.h.includes(f.height))&&(!r.m||f.misses.some(x=>r.m.includes(x))))ids.push(...r.t)});ids=[...new Set(ids.length?ids:['relax','tempo','short'])];return ids.map((id,i)=>{const a=logs.filter(x=>x.club===f.club&&x.tipId===id&&(f.misses.length===0||x.misses.some(m=>f.misses.includes(m)))),avg=a.length?a.reduce((s,x)=>s+(pts[x.result]??0),0)/a.length:null;return{id,title:T[id][0],detail:T[id][1],n:a.length,rate:avg===null?null:Math.round(avg*100),score:100-i+(avg??0)*80+Math.min(a.length,10)*2}}).sort((a,b)=>b.score-a.score).slice(0,3)}
export function insight(logs){const a={},b={};logs.forEach(x=>{x.misses.forEach(id=>{const n=MISS.find(m=>m.id===id)?.name||id,k=`${x.club}｜${n}`;a[k]=(a[k]||0)+1});if(x.tipId){b[x.tipId]??={n:0,s:0};b[x.tipId].n++;b[x.tipId].s+=pts[x.result]??0}});return{issues:Object.entries(a).sort((x,y)=>y[1]-x[1]).slice(0,3),tips:Object.entries(b).map(([id,v])=>({id,title:T[id]?.[0]||id,n:v.n,rate:Math.round(v.s/v.n*100)})).sort((x,y)=>y.rate-x.rate||y.n-x.n).slice(0,3)}}
